/* Auto-generated by tools/build_manifest.py — do not edit */
#ifndef POKESILVER_ASSETS_MANIFEST_H
#define POKESILVER_ASSETS_MANIFEST_H

#include <stddef.h>
#include <stdint.h>

#ifndef GB_ASSET_ENTRY_DEFINED
#define GB_ASSET_ENTRY_DEFINED
typedef struct {
    uint32_t rom_offset;
    uint32_t size;
    const char* path;
} GBAssetEntry;
#endif

#define POKESILVER_ASSETS_MANIFEST_COUNT 141

static const GBAssetEntry POKESILVER_ASSETS_MANIFEST[POKESILVER_ASSETS_MANIFEST_COUNT] = {
    { 0x00000000, 0x00000004, "code/rst0.bin" }, /* rst0 bank 00 */
    { 0x00000008, 0x00000003, "code/rst8.bin" }, /* rst8 bank 00 */
    { 0x00000010, 0x00000006, "code/rst10.bin" }, /* rst10 bank 00 */
    { 0x00000018, 0x00000001, "code/rst18.bin" }, /* rst18 bank 00 */
    { 0x00000020, 0x00000001, "code/rst20.bin" }, /* rst20 bank 00 */
    { 0x00000028, 0x0000000b, "code/rst28.bin" }, /* rst28 bank 00 */
    { 0x00000038, 0x00000001, "code/rst38.bin" }, /* rst38 bank 00 */
    { 0x00000040, 0x00000003, "code/vblank.bin" }, /* vblank bank 00 */
    { 0x00000048, 0x00000003, "code/lcd.bin" }, /* lcd bank 00 */
    { 0x00000050, 0x00000001, "code/timer.bin" }, /* timer bank 00 */
    { 0x00000058, 0x00000003, "code/serial.bin" }, /* serial bank 00 */
    { 0x00000060, 0x00000003, "code/joypad.bin" }, /* joypad bank 00 */
    { 0x00000100, 0x00000050, "code/header.bin" }, /* Header bank 00 */
    { 0x00000150, 0x00003e9e, "code/home.bin" }, /* Home bank 00 */
    { 0x00004000, 0x00003514, "code/bank1.bin" }, /* bank1 bank 01 */
    { 0x00008000, 0x00003c3e, "code/bank2.bin" }, /* bank2 bank 02 */
    { 0x0000c000, 0x00003a3c, "code/bank3.bin" }, /* bank3 bank 03 */
    { 0x00010000, 0x00003e03, "code/bank4.bin" }, /* bank4 bank 04 */
    { 0x00014000, 0x0000383e, "code/bank5.bin" }, /* bank5 bank 05 */
    { 0x00018000, 0x00003dbc, "data/tileset_data_1.bin" }, /* Tileset Data 1 bank 06 */
    { 0x0001c000, 0x0000030c, "data/roofs.bin" }, /* Roofs bank 07 */
    { 0x0001c30c, 0x00003540, "data/tileset_data_2.bin" }, /* Tileset Data 2 bank 07 */
    { 0x0001f84c, 0x00000771, "data/extra_songs_1.bin" }, /* Extra Songs 1 bank 07 */
    { 0x00020000, 0x00000181, "data/clock_reset.bin" }, /* Clock Reset bank 08 */
    { 0x00020181, 0x000037f0, "data/tileset_data_3.bin" }, /* Tileset Data 3 bank 08 */
    { 0x00023971, 0x0000008d, "data/catch_tutorial.bin" }, /* Catch Tutorial bank 08 */
    { 0x000239fe, 0x0000043f, "data/egg_moves.bin" }, /* Egg Moves bank 08 */
    { 0x00024000, 0x00003bd3, "code/bank9.bin" }, /* bank9 bank 09 */
    { 0x00028000, 0x00003ee3, "code/banka.bin" }, /* bankA bank 0a */
    { 0x0002c000, 0x00000a31, "code/bankb.bin" }, /* bankB bank 0b */
    { 0x00030000, 0x00003d90, "data/tileset_data_4.bin" }, /* Tileset Data 4 bank 0c */
    { 0x00034000, 0x00003fa0, "data/effect_commands.bin" }, /* Effect Commands bank 0d */
    { 0x00038000, 0x00003685, "data/enemy_trainers.bin" }, /* Enemy Trainers bank 0e */
    { 0x0003c000, 0x00003e9b, "battle/battle_core.bin" }, /* Battle Core bank 0f */
    { 0x00040000, 0x000027bd, "code/bank10.bin" }, /* bank10 bank 10 */
    { 0x000427bd, 0x0000169b, "data/evolutions_and_attacks.bin" }, /* Evolutions and Attacks bank 10 */
    { 0x00044000, 0x00000aa2, "code/bank11.bin" }, /* bank11 bank 11 */
    { 0x00048000, 0x000005e2, "data/pic_pointers.bin" }, /* Pic Pointers bank 12 */
    { 0x000485e2, 0x00003a1e, "gfx/pics_1.bin" }, /* Pics 1 bank 12 */
    { 0x00050000, 0x00003a83, "code/bank14.bin" }, /* bank14 bank 14 */
    { 0x00053a83, 0x00000092, "data/egg_pic.bin" }, /* Egg Pic bank 14 */
    { 0x00054000, 0x00003ffc, "gfx/pics_2.bin" }, /* Pics 2 bank 15 */
    { 0x00058000, 0x00003fff, "gfx/pics_3.bin" }, /* Pics 3 bank 16 */
    { 0x0005c000, 0x00003ffe, "gfx/pics_4.bin" }, /* Pics 4 bank 17 */
    { 0x00060000, 0x00003fcc, "gfx/pics_5.bin" }, /* Pics 5 bank 18 */
    { 0x00064000, 0x00003fde, "gfx/pics_6.bin" }, /* Pics 6 bank 19 */
    { 0x00068000, 0x00003ffe, "gfx/pics_7.bin" }, /* Pics 7 bank 1a */
    { 0x0006c000, 0x00003ffe, "gfx/pics_8.bin" }, /* Pics 8 bank 1b */
    { 0x00070000, 0x00004000, "gfx/pics_9.bin" }, /* Pics 9 bank 1c */
    { 0x00074000, 0x00003fff, "gfx/pics_10.bin" }, /* Pics 10 bank 1d */
    { 0x00078000, 0x00003ffe, "gfx/pics_11.bin" }, /* Pics 11 bank 1e */
    { 0x0007c000, 0x0000009c, "data/unown_pic_pointers.bin" }, /* Unown Pic Pointers bank 1f */
    { 0x0007c09c, 0x00003f63, "gfx/pics_12.bin" }, /* Pics 12 bank 1f */
    { 0x00080000, 0x000000c6, "data/trainer_pic_pointers.bin" }, /* Trainer Pic Pointers bank 20 */
    { 0x000800c6, 0x00003f3a, "gfx/pics_13.bin" }, /* Pics 13 bank 20 */
    { 0x00084000, 0x000028e7, "code/bank21.bin" }, /* bank21 bank 21 */
    { 0x000868e7, 0x00001316, "data/credits.bin" }, /* Credits bank 21 */
    { 0x0008c000, 0x00003e29, "code/bank23.bin" }, /* bank23 bank 23 */
    { 0x00090000, 0x00003f92, "code/bank24.bin" }, /* bank24 bank 24 */
    { 0x00094000, 0x000025f9, "data/maps.bin" }, /* Maps bank 25 */
    { 0x000965f9, 0x0000179d, "data/events.bin" }, /* Events bank 25 */
    { 0x00098000, 0x0000086b, "gfx/title_screen.bin" }, /* Title Screen bank 26 */
    { 0x000a8000, 0x00003fab, "data/map_blocks_1.bin" }, /* Map Blocks 1 bank 2a */
    { 0x000ac000, 0x00003f5a, "data/map_blocks_2.bin" }, /* Map Blocks 2 bank 2b */
    { 0x000b8000, 0x00001a43, "gfx/pics_14.bin" }, /* Pics 14 bank 2e */
    { 0x000ba300, 0x00001802, "code/bank2e.bin" }, /* bank2E bank 2e */
    { 0x000c0000, 0x00003fc0, "gfx/sprites_1.bin" }, /* Sprites 1 bank 30 */
    { 0x000c4000, 0x00003a40, "gfx/sprites_2.bin" }, /* Sprites 2 bank 31 */
    { 0x000c7a40, 0x0000029e, "code/bank31.bin" }, /* bank31 bank 31 */
    { 0x000c8000, 0x00003cbd, "code/bank32.bin" }, /* bank32 bank 32 */
    { 0x000cbcbd, 0x00000100, "data/the_end.bin" }, /* The End bank 32 */
    { 0x000cc000, 0x00003ce3, "data/move_animations.bin" }, /* Move Animations bank 33 */
    { 0x000cfce3, 0x00000166, "data/extra_songs_2.bin" }, /* Extra Songs 2 bank 33 */
    { 0x000d8000, 0x00000400, "data/font_inversed.bin" }, /* Font Inversed bank 36 */
    { 0x000dc000, 0x00001773, "data/map_blocks_3.bin" }, /* Map Blocks 3 bank 37 */
    { 0x000dd773, 0x00002720, "data/tileset_data_5.bin" }, /* Tileset Data 5 bank 37 */
    { 0x000e0000, 0x00003f74, "code/bank38.bin" }, /* bank38 bank 38 */
    { 0x000e4000, 0x000001e0, "data/copyright.bin" }, /* Copyright bank 39 */
    { 0x000e41e0, 0x00000270, "gfx/title_screen_2.bin" }, /* Title Screen 2 bank 39 */
    { 0x000e4450, 0x00003070, "code/bank39.bin" }, /* bank39 bank 39 */
    { 0x000e8000, 0x00001492, "data/audio.bin" }, /* Audio bank 3a */
    { 0x000e9492, 0x00002b25, "data/songs_1.bin" }, /* Songs 1 bank 3a */
    { 0x000ec000, 0x00003ef5, "data/songs_2.bin" }, /* Songs 2 bank 3b */
    { 0x000f0000, 0x00000941, "data/songs_3.bin" }, /* Songs 3 bank 3c */
    { 0x000f0941, 0x00001e06, "audio/sound_effects.bin" }, /* Sound Effects bank 3c */
    { 0x000f2747, 0x0000182f, "data/cries.bin" }, /* Cries bank 3c */
    { 0x000f4000, 0x00003ef3, "data/songs_4.bin" }, /* Songs 4 bank 3d */
    { 0x000f8000, 0x000035be, "code/bank3e.bin" }, /* bank3E bank 3e */
    { 0x000fb5be, 0x000000d0, "gfx/shrink_pics.bin" }, /* Shrink Pics bank 3e */
    { 0x000fb68e, 0x00000905, "data/bank3e_2.bin" }, /* bank3E_2 bank 3e */
    { 0x000fc000, 0x00001e20, "code/bank3f.bin" }, /* bank3F bank 3f */
    { 0x00100000, 0x0000221d, "data/standard_scripts.bin" }, /* Standard Scripts bank 40 */
    { 0x00104000, 0x0000214d, "data/phone_scripts.bin" }, /* Phone Scripts bank 41 */
    { 0x00108000, 0x00001dca, "data/map_scripts_1.bin" }, /* Map Scripts 1 bank 42 */
    { 0x0010c000, 0x00003198, "data/map_scripts_2.bin" }, /* Map Scripts 2 bank 43 */
    { 0x00110000, 0x000030cb, "data/map_scripts_3.bin" }, /* Map Scripts 3 bank 44 */
    { 0x00114000, 0x00002f31, "data/map_scripts_4.bin" }, /* Map Scripts 4 bank 45 */
    { 0x00118000, 0x00002358, "data/map_scripts_5.bin" }, /* Map Scripts 5 bank 46 */
    { 0x0011c000, 0x00000a41, "data/map_scripts_6.bin" }, /* Map Scripts 6 bank 47 */
    { 0x00120000, 0x0000259f, "data/map_scripts_7.bin" }, /* Map Scripts 7 bank 48 */
    { 0x00124000, 0x00001f51, "data/map_scripts_8.bin" }, /* Map Scripts 8 bank 49 */
    { 0x00128000, 0x00002018, "data/map_scripts_9.bin" }, /* Map Scripts 9 bank 4a */
    { 0x0012c000, 0x000029bb, "data/map_scripts_10.bin" }, /* Map Scripts 10 bank 4b */
    { 0x00130000, 0x00001f26, "data/map_scripts_11.bin" }, /* Map Scripts 11 bank 4c */
    { 0x00134000, 0x00001e5a, "data/map_scripts_12.bin" }, /* Map Scripts 12 bank 4d */
    { 0x00138000, 0x00002176, "data/map_scripts_13.bin" }, /* Map Scripts 13 bank 4e */
    { 0x0013c000, 0x000024c4, "data/map_scripts_14.bin" }, /* Map Scripts 14 bank 4f */
    { 0x00140000, 0x000018ed, "data/map_scripts_15.bin" }, /* Map Scripts 15 bank 50 */
    { 0x00144000, 0x00001df1, "data/map_scripts_16.bin" }, /* Map Scripts 16 bank 51 */
    { 0x00148000, 0x00001cb4, "data/map_scripts_17.bin" }, /* Map Scripts 17 bank 52 */
    { 0x0014c000, 0x00001e6e, "data/map_scripts_18.bin" }, /* Map Scripts 18 bank 53 */
    { 0x00150000, 0x00001aa3, "data/map_scripts_19.bin" }, /* Map Scripts 19 bank 54 */
    { 0x00154000, 0x000015a7, "data/map_scripts_20.bin" }, /* Map Scripts 20 bank 55 */
    { 0x00158000, 0x00003634, "data/map_scripts_21.bin" }, /* Map Scripts 21 bank 56 */
    { 0x0015c000, 0x00003213, "data/map_scripts_22.bin" }, /* Map Scripts 22 bank 57 */
    { 0x00164000, 0x00001fc7, "data/map_scripts_23.bin" }, /* Map Scripts 23 bank 59 */
    { 0x00168000, 0x00001f3c, "data/map_scripts_24.bin" }, /* Map Scripts 24 bank 5a */
    { 0x0016c000, 0x0000295d, "data/map_scripts_25.bin" }, /* Map Scripts 25 bank 5b */
    { 0x00170000, 0x00001609, "data/map_scripts_26.bin" }, /* Map Scripts 26 bank 5c */
    { 0x00174000, 0x00001e2d, "data/map_scripts_27.bin" }, /* Map Scripts 27 bank 5d */
    { 0x00178000, 0x00002acb, "data/map_scripts_28.bin" }, /* Map Scripts 28 bank 5e */
    { 0x0017c000, 0x000011d7, "data/map_scripts_29.bin" }, /* Map Scripts 29 bank 5f */
    { 0x00180000, 0x00002666, "data/map_scripts_30.bin" }, /* Map Scripts 30 bank 60 */
    { 0x00184000, 0x00001922, "data/map_scripts_31.bin" }, /* Map Scripts 31 bank 61 */
    { 0x00188000, 0x00000eae, "data/map_scripts_32.bin" }, /* Map Scripts 32 bank 62 */
    { 0x00190000, 0x00002145, "text/text_1.bin" }, /* Text 1 bank 64 */
    { 0x00194000, 0x000020c2, "text/text_2.bin" }, /* Text 2 bank 65 */
    { 0x00198000, 0x00000a45, "text/text_3.bin" }, /* Text 3 bank 66 */
    { 0x001a0000, 0x00001b85, "text/pokedex_entries_001_064.bin" }, /* Pokedex Entries 001-064 bank 68 */
    { 0x001a4000, 0x00001bc9, "text/pokedex_entries_065_128.bin" }, /* Pokedex Entries 065-128 bank 69 */
    { 0x001a8000, 0x00001bce, "text/pokedex_entries_129_192.bin" }, /* Pokedex Entries 129-192 bank 6a */
    { 0x001ac000, 0x00001984, "text/pokedex_entries_193_251.bin" }, /* Pokedex Entries 193-251 bank 6b */
    { 0x001b0000, 0x00001ee1, "text/names.bin" }, /* Names bank 6c */
    { 0x001b4000, 0x000021f3, "data/move_descriptions.bin" }, /* Move Descriptions bank 6d */
    { 0x001b8000, 0x00001544, "data/item_descriptions.bin" }, /* Item Descriptions bank 6e */
    { 0x001c0000, 0x00000407, "code/bank70.bin" }, /* bank70 bank 70 */
    { 0x001c0407, 0x00000606, "data/tileset_data_6.bin" }, /* Tileset Data 6 bank 70 */
    { 0x001c0a0d, 0x00000436, "data/bank70_2.bin" }, /* bank70_2 bank 70 */
    { 0x001c0e43, 0x000002e4, "data/pok_gear_gfx.bin" }, /* Pokégear GFX bank 70 */
    { 0x001c1127, 0x00000565, "data/credits_strings.bin" }, /* Credits Strings bank 70 */
    { 0x001ffdf8, 0x00000208, "data/stadium_2_checksums.bin" }, /* Stadium 2 Checksums bank 7f */
};

#endif
