/* Generated by gbrecomp from pokesilver */
#include "pokesilver_internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void pokesilver_dispatch_00(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_01(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_02(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_03(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_04(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_05(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_06(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_07(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_08(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_09(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_0f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_10(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_11(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_12(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_13(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_14(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_15(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_16(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_17(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_18(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_19(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_1f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_20(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_21(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_22(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_23(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_24(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_25(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_26(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_27(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_28(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_29(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_2f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_30(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_31(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_32(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_33(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_34(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_35(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_36(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_37(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_38(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_39(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_3f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_40(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_41(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_42(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_43(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_44(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_45(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_46(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_47(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_48(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_49(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_4f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_50(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_51(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_52(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_53(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_54(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_55(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_56(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_57(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_58(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_59(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_5f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_60(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_61(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_62(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_63(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_64(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_65(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_66(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_67(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_68(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_69(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_6f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_70(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_71(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_72(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_73(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_74(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_75(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_76(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_77(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_78(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_79(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7a(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7b(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7c(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7d(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7e(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_7f(GBContext* ctx, uint16_t addr, uint8_t bank);
void pokesilver_dispatch_ff(GBContext* ctx, uint16_t addr, uint8_t bank);

static uint8_t pokesilver__ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff81) != 0xc3) return 0;
    if (gb_read8(ctx, 0xff82) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff83) != 0x46) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff85) != 0x28) return 0;
    if (gb_read8(ctx, 0xff86) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff87) != 0x20) return 0;
    if (gb_read8(ctx, 0xff88) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff89) != 0xc9) return 0;
    return 1;
}

static uint8_t pokesilver__try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint8_t bank) {
    if (addr >= 0xff80 && addr < 0xff8a) {
        if (!pokesilver__ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                pokesilver_dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void pokesilver__gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        addr = ctx->pc;
        uint8_t bank = ctx->rom_bank;
        if (addr < 0x4000) bank = 0;
        if (gbrt_instruction_limit > 0 && gbrt_instruction_count >= gbrt_instruction_limit) {
            fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
            exit(0);
        }
        gbrt_instruction_count++;
        gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (pokesilver__try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_note_dispatch_fallback(ctx, bank, addr);
            gb_interpret(ctx, addr);
            if (ctx->single_step_mode || ctx->stopped) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: pokesilver_dispatch_00(ctx, addr, bank); break;
            case 0x01: pokesilver_dispatch_01(ctx, addr, bank); break;
            case 0x02: pokesilver_dispatch_02(ctx, addr, bank); break;
            case 0x03: pokesilver_dispatch_03(ctx, addr, bank); break;
            case 0x04: pokesilver_dispatch_04(ctx, addr, bank); break;
            case 0x05: pokesilver_dispatch_05(ctx, addr, bank); break;
            case 0x06: pokesilver_dispatch_06(ctx, addr, bank); break;
            case 0x07: pokesilver_dispatch_07(ctx, addr, bank); break;
            case 0x08: pokesilver_dispatch_08(ctx, addr, bank); break;
            case 0x09: pokesilver_dispatch_09(ctx, addr, bank); break;
            case 0x0a: pokesilver_dispatch_0a(ctx, addr, bank); break;
            case 0x0b: pokesilver_dispatch_0b(ctx, addr, bank); break;
            case 0x0c: pokesilver_dispatch_0c(ctx, addr, bank); break;
            case 0x0d: pokesilver_dispatch_0d(ctx, addr, bank); break;
            case 0x0e: pokesilver_dispatch_0e(ctx, addr, bank); break;
            case 0x0f: pokesilver_dispatch_0f(ctx, addr, bank); break;
            case 0x10: pokesilver_dispatch_10(ctx, addr, bank); break;
            case 0x11: pokesilver_dispatch_11(ctx, addr, bank); break;
            case 0x12: pokesilver_dispatch_12(ctx, addr, bank); break;
            case 0x13: pokesilver_dispatch_13(ctx, addr, bank); break;
            case 0x14: pokesilver_dispatch_14(ctx, addr, bank); break;
            case 0x15: pokesilver_dispatch_15(ctx, addr, bank); break;
            case 0x16: pokesilver_dispatch_16(ctx, addr, bank); break;
            case 0x17: pokesilver_dispatch_17(ctx, addr, bank); break;
            case 0x18: pokesilver_dispatch_18(ctx, addr, bank); break;
            case 0x19: pokesilver_dispatch_19(ctx, addr, bank); break;
            case 0x1a: pokesilver_dispatch_1a(ctx, addr, bank); break;
            case 0x1b: pokesilver_dispatch_1b(ctx, addr, bank); break;
            case 0x1c: pokesilver_dispatch_1c(ctx, addr, bank); break;
            case 0x1d: pokesilver_dispatch_1d(ctx, addr, bank); break;
            case 0x1e: pokesilver_dispatch_1e(ctx, addr, bank); break;
            case 0x1f: pokesilver_dispatch_1f(ctx, addr, bank); break;
            case 0x20: pokesilver_dispatch_20(ctx, addr, bank); break;
            case 0x21: pokesilver_dispatch_21(ctx, addr, bank); break;
            case 0x22: pokesilver_dispatch_22(ctx, addr, bank); break;
            case 0x23: pokesilver_dispatch_23(ctx, addr, bank); break;
            case 0x24: pokesilver_dispatch_24(ctx, addr, bank); break;
            case 0x25: pokesilver_dispatch_25(ctx, addr, bank); break;
            case 0x26: pokesilver_dispatch_26(ctx, addr, bank); break;
            case 0x27: pokesilver_dispatch_27(ctx, addr, bank); break;
            case 0x28: pokesilver_dispatch_28(ctx, addr, bank); break;
            case 0x29: pokesilver_dispatch_29(ctx, addr, bank); break;
            case 0x2a: pokesilver_dispatch_2a(ctx, addr, bank); break;
            case 0x2b: pokesilver_dispatch_2b(ctx, addr, bank); break;
            case 0x2c: pokesilver_dispatch_2c(ctx, addr, bank); break;
            case 0x2d: pokesilver_dispatch_2d(ctx, addr, bank); break;
            case 0x2e: pokesilver_dispatch_2e(ctx, addr, bank); break;
            case 0x2f: pokesilver_dispatch_2f(ctx, addr, bank); break;
            case 0x30: pokesilver_dispatch_30(ctx, addr, bank); break;
            case 0x31: pokesilver_dispatch_31(ctx, addr, bank); break;
            case 0x32: pokesilver_dispatch_32(ctx, addr, bank); break;
            case 0x33: pokesilver_dispatch_33(ctx, addr, bank); break;
            case 0x34: pokesilver_dispatch_34(ctx, addr, bank); break;
            case 0x35: pokesilver_dispatch_35(ctx, addr, bank); break;
            case 0x36: pokesilver_dispatch_36(ctx, addr, bank); break;
            case 0x37: pokesilver_dispatch_37(ctx, addr, bank); break;
            case 0x38: pokesilver_dispatch_38(ctx, addr, bank); break;
            case 0x39: pokesilver_dispatch_39(ctx, addr, bank); break;
            case 0x3a: pokesilver_dispatch_3a(ctx, addr, bank); break;
            case 0x3b: pokesilver_dispatch_3b(ctx, addr, bank); break;
            case 0x3c: pokesilver_dispatch_3c(ctx, addr, bank); break;
            case 0x3d: pokesilver_dispatch_3d(ctx, addr, bank); break;
            case 0x3e: pokesilver_dispatch_3e(ctx, addr, bank); break;
            case 0x3f: pokesilver_dispatch_3f(ctx, addr, bank); break;
            case 0x40: pokesilver_dispatch_40(ctx, addr, bank); break;
            case 0x41: pokesilver_dispatch_41(ctx, addr, bank); break;
            case 0x42: pokesilver_dispatch_42(ctx, addr, bank); break;
            case 0x43: pokesilver_dispatch_43(ctx, addr, bank); break;
            case 0x44: pokesilver_dispatch_44(ctx, addr, bank); break;
            case 0x45: pokesilver_dispatch_45(ctx, addr, bank); break;
            case 0x46: pokesilver_dispatch_46(ctx, addr, bank); break;
            case 0x47: pokesilver_dispatch_47(ctx, addr, bank); break;
            case 0x48: pokesilver_dispatch_48(ctx, addr, bank); break;
            case 0x49: pokesilver_dispatch_49(ctx, addr, bank); break;
            case 0x4a: pokesilver_dispatch_4a(ctx, addr, bank); break;
            case 0x4b: pokesilver_dispatch_4b(ctx, addr, bank); break;
            case 0x4c: pokesilver_dispatch_4c(ctx, addr, bank); break;
            case 0x4d: pokesilver_dispatch_4d(ctx, addr, bank); break;
            case 0x4e: pokesilver_dispatch_4e(ctx, addr, bank); break;
            case 0x4f: pokesilver_dispatch_4f(ctx, addr, bank); break;
            case 0x50: pokesilver_dispatch_50(ctx, addr, bank); break;
            case 0x51: pokesilver_dispatch_51(ctx, addr, bank); break;
            case 0x52: pokesilver_dispatch_52(ctx, addr, bank); break;
            case 0x53: pokesilver_dispatch_53(ctx, addr, bank); break;
            case 0x54: pokesilver_dispatch_54(ctx, addr, bank); break;
            case 0x55: pokesilver_dispatch_55(ctx, addr, bank); break;
            case 0x56: pokesilver_dispatch_56(ctx, addr, bank); break;
            case 0x57: pokesilver_dispatch_57(ctx, addr, bank); break;
            case 0x58: pokesilver_dispatch_58(ctx, addr, bank); break;
            case 0x59: pokesilver_dispatch_59(ctx, addr, bank); break;
            case 0x5a: pokesilver_dispatch_5a(ctx, addr, bank); break;
            case 0x5b: pokesilver_dispatch_5b(ctx, addr, bank); break;
            case 0x5c: pokesilver_dispatch_5c(ctx, addr, bank); break;
            case 0x5d: pokesilver_dispatch_5d(ctx, addr, bank); break;
            case 0x5e: pokesilver_dispatch_5e(ctx, addr, bank); break;
            case 0x5f: pokesilver_dispatch_5f(ctx, addr, bank); break;
            case 0x60: pokesilver_dispatch_60(ctx, addr, bank); break;
            case 0x61: pokesilver_dispatch_61(ctx, addr, bank); break;
            case 0x62: pokesilver_dispatch_62(ctx, addr, bank); break;
            case 0x63: pokesilver_dispatch_63(ctx, addr, bank); break;
            case 0x64: pokesilver_dispatch_64(ctx, addr, bank); break;
            case 0x65: pokesilver_dispatch_65(ctx, addr, bank); break;
            case 0x66: pokesilver_dispatch_66(ctx, addr, bank); break;
            case 0x67: pokesilver_dispatch_67(ctx, addr, bank); break;
            case 0x68: pokesilver_dispatch_68(ctx, addr, bank); break;
            case 0x69: pokesilver_dispatch_69(ctx, addr, bank); break;
            case 0x6a: pokesilver_dispatch_6a(ctx, addr, bank); break;
            case 0x6b: pokesilver_dispatch_6b(ctx, addr, bank); break;
            case 0x6c: pokesilver_dispatch_6c(ctx, addr, bank); break;
            case 0x6d: pokesilver_dispatch_6d(ctx, addr, bank); break;
            case 0x6e: pokesilver_dispatch_6e(ctx, addr, bank); break;
            case 0x6f: pokesilver_dispatch_6f(ctx, addr, bank); break;
            case 0x70: pokesilver_dispatch_70(ctx, addr, bank); break;
            case 0x71: pokesilver_dispatch_71(ctx, addr, bank); break;
            case 0x72: pokesilver_dispatch_72(ctx, addr, bank); break;
            case 0x73: pokesilver_dispatch_73(ctx, addr, bank); break;
            case 0x74: pokesilver_dispatch_74(ctx, addr, bank); break;
            case 0x75: pokesilver_dispatch_75(ctx, addr, bank); break;
            case 0x76: pokesilver_dispatch_76(ctx, addr, bank); break;
            case 0x77: pokesilver_dispatch_77(ctx, addr, bank); break;
            case 0x78: pokesilver_dispatch_78(ctx, addr, bank); break;
            case 0x79: pokesilver_dispatch_79(ctx, addr, bank); break;
            case 0x7a: pokesilver_dispatch_7a(ctx, addr, bank); break;
            case 0x7b: pokesilver_dispatch_7b(ctx, addr, bank); break;
            case 0x7c: pokesilver_dispatch_7c(ctx, addr, bank); break;
            case 0x7d: pokesilver_dispatch_7d(ctx, addr, bank); break;
            case 0x7e: pokesilver_dispatch_7e(ctx, addr, bank); break;
            case 0x7f: pokesilver_dispatch_7f(ctx, addr, bank); break;
            case 0xff: pokesilver_dispatch_ff(ctx, addr, bank); break;
            default: gbrt_note_dispatch_fallback(ctx, bank, addr); gb_interpret(ctx, addr); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void pokesilver__gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    pokesilver__gb_dispatch(ctx, addr);
}

/* Extern reference to ROM data */
extern uint8_t pokesilver__rom_data[];
extern const size_t pokesilver__rom_size;

const GBConfig* pokesilver_default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_CGB,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = true,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
    };
    return &config;
}

void pokesilver_init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, pokesilver__rom_data, pokesilver__rom_size);
    /* Set MBC type from header */
    ctx->mbc_type = pokesilver__rom_data[0x147];
    gb_context_reset(ctx, true);
}

void pokesilver_run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    pokesilver__gb_dispatch(ctx, ctx->pc);
}
