/* Generated by gbrecomp */
#ifndef pokesilver_H
#define pokesilver_H

#include "gbrt.h"

const GBConfig* pokesilver_default_config(void);
void pokesilver_run(GBContext* ctx);
void pokesilver_init(GBContext* ctx);
int pokesilver_main(int argc, char* argv[]);

#endif
